# coding: utf-8

"""
    Snowflake SQL API V2

    The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database.   Contact Support:  Name: Snowflake, Inc.  Email: support@snowflake.com  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import
from email.quoprimime import body_check

import unittest

import snowflake_sql_api_client
from snowflake_sql_api_client.api.apiv2statements_api import Apiv2statementsApi  # noqa: E501
from snowflake_sql_api_client.rest import ApiException


class TestApiv2statementsApi(unittest.TestCase):
    """Apiv2statementsApi unit test stubs"""

    token = ""

    def setUp(self):
        self.api = Apiv2statementsApi()  # noqa: E501
        http_config = self.api.api_client.configuration

        http_config.host = "https://abc.com"
        http_config.api_key["Authorization"] = self.token
        http_config.api_key_prefix["Authorization"] = "Bearer"


    def tearDown(self):
        pass

    def test_api_v2_statements_post(self):
        """Test case for api_v2_statements_post

        Submits a SQL statement for execution.  # noqa: E501
        """

        sql_query = """{
            "statement": "select top 10 * from WELL_NPT_GOLD",
            "database": "DB",
            "schema": "DBSchema",
            "warehouse": "DB_WH",
            "role": "ANALYST"
            }
            """

        self.api.api_v2_statements_post(body = sql_query)
        pass


if __name__ == '__main__':
    unittest.main()
