# coding: utf-8

"""
    Snowflake SQL API V2

    The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database.     # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import snowflake_sql_api_client
from snowflake_sql_api_client.api.apiv2statements__statement_handle_api import Apiv2statementsStatementHandleApi  # noqa: E501
from snowflake_sql_api_client.rest import ApiException


class TestApiv2statementsStatementHandleApi(unittest.TestCase):
    """Apiv2statementsStatementHandleApi unit test stubs"""

    def setUp(self):
        self.api = Apiv2statementsStatementHandleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_statements_statement_handle_cancel_post(self):
        """Test case for api_v2_statements_statement_handle_cancel_post

        Cancels the execution of a statement.  # noqa: E501
        """
        pass

    def test_api_v2_statements_statement_handle_get(self):
        """Test case for api_v2_statements_statement_handle_get

        Checks the status of the execution of a statement  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
